### ISSUE TITLE
Audio co-operation

### ISSUE THREAD

**Issue by mekanix** [Wamphyre/BSD-XFCE#11]
I would leave a replay to your comment, but I'm afraid you wouldn't see it. I know issue is not the ideal place for communication but I've got no other options. Anyway, I'd like to propose a project where we compose, record and mix everything on FreeBSD. If you're up to it, can you please send me an email (it's on my website) so we can arrange something? I'm sure we can find some common ground :o)

**Comment by Wamphyre** [comment]
Just sent an email!
