### ISSUE TITLE
Feature Request: Linux Version 

### ISSUE THREAD

**Issue by 2KAbhishek** [Wamphyre/BSD-XFCE#2]
Great job @Wamphyre!!

Would like to know if you have plans for adding a Linux version, if not I'd like to give it a shot.

Do you have any steps/pointers?

**Comment by Wamphyre** [comment]
Hi!

If you're looking the Linux version of `macOS-XFCE-Skinpack` it exists here: 

https://github.com/libredeb/xfce4-macOS_skinpack

My FreeBSD version is based and adapted from this original work.

Greetings!
