### ISSUE TITLE
GeForce 210 doesn´t boot

### ISSUE THREAD

**Issue by FEF7691** [Wamphyre/BSD-XFCE#3]
The installation process completes successfully, but X never starts.

**Comment by Wamphyre** [comment]
Hi @FEF7691 thank you very much for your feedback.

That's related with the `nvidia-driver` used in the main script (`510.60.02`), it is not compatible with your GPU model.

Please, try the following:

`pkg remove -y nvidia-driver && pkg autoremove -y`
`cd /usr/ports/x11/nvidia-driver-340 && make install clean BATCH=YES`
`nvidia-xconfig`
`reboot`

The `340.108` driver is compatible with the Geforce 200 GPU Series, so after installation and reboot X must start correctly.

Greetings!

**Comment by FEF7691** [comment]
Unfortunately it doesn't work. I followed your instructions, but it won't
start X.
I've been trying to make FreeBSD work as a desktop for some time now, with
the hardware I have available, but I've come to the conclusion that FreeBSD
is very immature in this particular area. The common user wants to install
and walk away, but GhostBSD, NomadBSD and these scripts like yours don't
work with my hardware. I tried with another old PC, and it doesn't work
either.
I have an Intel motherboard with an onboard UHD 630 graphics card, but
since I was not successful either, I decided to try the GeForce 210 card
that I had on hand.
It's a shame that FreeBSD doesn't offer a solid and trouble-free solution
for the desktop user. It must be said: we are 10 light years away from a
distro like Ubuntu.
Anyway, I appreciate your effort and dedication, but I don't want to waste
any more time.
Kind regards and good luck

**Comment by Wamphyre** [comment]
I'm sorry to read that :( but, I would like to give another shot.

After install `nvidia-driver-340` , please change `nvidia-modeset_load="YES"` to `nvidia_load="YES"` in `/boot/loader.conf`

With this, we're changing the behaviour and the mode as the kernel module loads at boot.

Also check in your home directory if `.xinitrc` exists (must be). If not, do the following:

`touch .xinitrc`
`echo "exec xfce4-session" >> .xinitrc`

Good luck, and thanks for open the issue!

**Comment by FEF7691** [comment]
I have made the changes that you suggested but It doesn't work....
After booting I get the normal prompt.
Very very frustrating.
Thanks anyway

**Comment by Wamphyre** [comment]
Yes, that's frustrating but must have a solution, because your GPU and the driver are supported.

I will investigate about that with an older Nvidia card. If I find some hints I will update this issue.

Sorry @FEF7691 I really appreciate your collaboration and your kindness.

Regards!

**Comment by FEF7691** [comment]
From what I could read out there in some forum, the problem seems to me to be related to the nvidia driver and the new/latest version of X.
One thought I have is that we may be forcing things, pretending that FreeBSD works fine as a desktop, knowing that the drivers for a lot of VGA cards are not mature enough for that. With this same hardware (intel uhd 630 and GF210), I have tried dozens of Linux distros, all working perfectly without the slightest problem.
That said, I'm going to format the drive with FreeBSD so I won't be able to run any further tests.
Again, thanks for your time.
Cheers
