### ISSUE TITLE
Failed to execute login command

### ISSUE THREAD

**Issue by gordo1337** [Wamphyre/BSD-XFCE#5]
After deploying xfce_desktop.sh and rebooting. 
The GUI login page shows up. 
But unable to login.

**Comment by gordo1337** [comment]
Found a workaround to Tty1 terminal CTRL+ALT+F2

**Comment by gordo1337** [comment]
Found a workaround to terminal with keybinds CTRL+ALT+F2 for Tty2

**Comment by Wamphyre** [comment]
Hi @gordo1337 ! Are you triying to login with your regular user or root? 

Do your regular user use a custom home directory or permissions? 

I will need more info about your base installation, user permissions, etc. A log extract will be helpful to debug.

**Comment by Wamphyre** [comment]
Can't be reproduced. Need more info.

**Comment by Wamphyre** [comment]
Can't be reproduced. Need more info.

**Comment by Wamphyre** [comment]
Can't be reproduced. Need more info.

**Comment by gordo1337** [comment]
Sorry! Been working so havent had time. But i did a workaround with F3 i think so i could bypass the login and go straight to terminal.
