### ISSUE TITLE
There is no need to use sysrc hald_enable="YES" 

### ISSUE THREAD

**Issue by ykla** [Wamphyre/BSD-XFCE#6]
hal has been removed for a long time.

please see https://www.freshports.org/sysutils/hal.

There is no need to use `sysrc hald_enable="YES" `.

https://github.com/Wamphyre/BSD-XFCE/blob/main/xfce_desktop.sh line 53.

**Comment by Wamphyre** [comment]
Hi @ykla , I just tested in my devbox and everything runs good, so, I just removed HAL from the main script.

Thank you!
