### ISSUE TITLE
Network issues

### ISSUE THREAD

**Issue by Drack112** [Wamphyre/BSD-XFCE#8]
After the normal installation, along with the configuration and everything else, I've been noticing that the network ends up dropping around 30 or 15 minutes of use, it's a quick drop that comes back in at least 10 seconds. But I wanted to know what could be causing this, I don't know if it could be DHCP or something else.

Any idea?

**Comment by Wamphyre** [comment]
Hi @Drack112 what net interface are you using? With the default settings you must have an stable and fast connection with FreeBSD 13.1

Thanks for your contact!

**Comment by Drack112** [comment]
Hi! I just have it do the normal install again and it's works :)

Now without dropping
