### ISSUE TITLE
(Support) Intel Graphics

### ISSUE THREAD

**Issue by eribertto** [Wamphyre/BSD-XFCE#9]
Hello @Wamphyre  
I get it in your README the disclaimer "No AMD/Intel support for now". But it would be great if Intel GPUs will be included in the future so I can try it on my Intel machines, both laptop and NUC. I have Intel Mesa integrated btw. I looked at the install script and in the compile section how about changing the nvidia instances to drm-kmod, is it as simple as that or more complicated? I'm just new to FreeBSD being a long time Linux distro hopper myself. In any case I love to hear your thoughts. I'm trying to transition to FreeBSD and somehow I'm successful since I got it working in my Thinkpad laptop and also as Vbox guest. Keep up the good work sir :+1:

**Comment by Wamphyre** [comment]
Just added support for latest Intel / AMD and NVIDIA drivers :) please check the new readme file.

Greetings!
